### ISSUE TITLE
import environs fails on Ubuntu 16.04.6 LTS with Python 3.5.2

### ISSUE THREAD

**Issue by alxrmorozov** [sloria/environs#142]
```console
user@2fcfee34b4bd:~$ virtualenv -p python3 venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/user/venv/bin/python3
Also creating executable in /home/user/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
user@2fcfee34b4bd:~$ . venv/bin/activate
(venv) user@2fcfee34b4bd:~$ pip install environs
Collecting environs
  Downloading environs-7.2.0-py2.py3-none-any.whl (11 kB)
Collecting python-dotenv
  Downloading python_dotenv-0.12.0-py2.py3-none-any.whl (17 kB)
Collecting marshmallow>=2.7.0
  Downloading marshmallow-3.5.0-py2.py3-none-any.whl (45 kB)
     |################################| 45 kB 257 kB/s
Installing collected packages: python-dotenv, marshmallow, environs
Successfully installed environs-7.2.0 marshmallow-3.5.0 python-dotenv-0.12.0
(venv) user@2fcfee34b4bd:~$ python
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import environs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venv/lib/python3.5/site-packages/environs/__init__.py", line 31, in <module>
    Subcast = typing.Union[typing.Type, typing.Callable[..., _T]]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/home/user/venv/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
>>>
```

**Comment by sloria** [comment]
Can you try using a new Python version. Earlier point versions of Python 3.5 had some bugs within the `typing` module that were fixed. IIRC a number of issues were resolved in 3.5.4.

**Comment by alxrmorozov** [comment]
I tried 3.5.3 and it works with it

**Comment by sloria** [comment]
Great; we should update the `python_requires` in the setup.py metadata to pin to `>=3.5.3`.

**Comment by manoadamro** [comment]
also doesn't work in windows. everything else in my requirements imports fine, just not environs
